### ISSUE TITLE
Comment after space gets lost

### ISSUE THREAD

**Issue by hwalinga** [ctSkennerton/bioawk#2]
Thanks for opening issues here. 

So, this bug has been somewhere introduced in this fork as it is not present in the original by lh3. 

Increasingly more often a fasta header has an identifier and then a space for comments. Using `bioawk -cfastx` this will then be separated in the variable `$name` and `$comment`. 

However, whenever the comment consists of multiple words (a string with spaces) currently in this fork `$comment` contains only a single (seemingly random) word from the complete comment string.

For example (fasta)

    echo -e ">ID10 comment about this\nA" | bioawk -cfastx '{printf "%s,%s\n", $name, $comment}'

Current output (second word of comment):

    ID10,about

Expected output (by original bioawk):

    ID10,comment about this

----

Second example (real world fastq)

    wget -O- https://termbin.com/n558 | ./bioawk -cfastx '{printf "%s,%s\n", $name, $comment}'

Current output (first word of comment):
  
    Barcode,18

Expected output (by original bioawk):

    Barcode,18 (forward) 5f6139e7-fd55-4826-9dfa-b4cf04d18f10 runid=6abe51788a456aa4738d2261997a4d2f37646cb3 sampleid=NOB3378run1HS read=28548 ch=70 start time=2019-03-21T21:25:07Z barcode=barcode15

**Comment by ctSkennerton** [comment]
I think I've fixed it with latest commits.
